name: flutter_scale_kit
description: A high-performance responsive design package for Flutter with intelligent caching, const widget support, and device-specific scaling strategies. Similar to flutter_screenutil but optimized for better performance.
version: 1.0.1
homepage: https://github.com/fodilfliti/flutter_scale_kit
repository: https://github.com/fodilfliti/flutter_scale_kit

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # No assets or fonts needed for this package
